### ISSUE TITLE
Trying this script

### ISSUE THREAD

**Issue by ogmkp** [International-Anglican-Church/visca-joystick#3]
Hi.

I'm trying this script but I don't understand this result when I press X:

```
$ python3 main.py 
Pan & Tilt: Left stick | Invert tilt: Click left stick'
Zoom: Right stick
Brightness: Up: Right trigger, Down: Left trigger
Manual focus: Left and right bumpers
Select camera 1: X, 2: ◯, 3: △
Exit: Options
Press triangle to configure cameras or any other button to skip
Traceback (most recent call last):
  File "/home/ogal/visca-joystick/main.py", line 155, in <module>
    cam = connect_to_camera(0)
  File "/home/ogal/visca-joystick/main.py", line 106, in connect_to_camera
    cam = Camera(ips[cam_index])
  File "/home/ogal/.local/lib/python3.9/site-packages/visca_over_ip/caching_camera.py", line 9, in __init__
    super().__init__(ip, port)
  File "/home/ogal/.local/lib/python3.9/site-packages/visca_over_ip/camera.py", line 30, in __init__
    self.reset_sequence_number()
  File "/home/ogal/.local/lib/python3.9/site-packages/visca_over_ip/camera.py", line 98, in reset_sequence_number
    self._sock.sendto(message, self._location)
socket.gaierror: [Errno -2] Name or service not known
```
I'm on Debian 11.

Thanks.

**Comment by Yook74** [comment]
Presumably you've edited [the camera IPs in config.py](https://github.com/International-Anglican-Church/visca-joystick/blob/003b9f547e4bcd89002cedfcd992f94955be9e19/config.py#L16) what did you set them to?

**Comment by ogmkp** [comment]
Yes I edited 172.16.0.20 by the camera IP but can't find the port ?

**Comment by Yook74** [comment]
What did you change the ips to? Can you please send me your code on that line?

**Comment by ogmkp** [comment]
Sure:
ips = [f'192.168.10.40{idx + 1}' for idx in range(num_cams)]
.40 is the camera. It run VISCA on udp.

**Comment by Yook74** [comment]
change that to `ips = ['192.168.10.40']` and while you're at it set `num_cams = 1`

The way you have it set up it's trying to connect to three cameras on 192.168.10.401, 192.168.10.402, and 192.168.10.403. This is incorrect.

**Comment by ogmkp** [comment]
Ok, give me some time to test.

**Comment by ogmkp** [comment]
I modified the config.py as requested, now when I run main.py the controller is no longer recognized. I put back the original config.py and the controller is still not recognized. However the controller event is present and it works, confirmed with evtest.

**Comment by Yook74** [comment]
What controller are you using? What error message are you getting?

**Comment by ogmkp** [comment]
No error message, when I press X, the prompt stay on:
`Press triangle to configure cameras or any other button to skip
`
I'm using a PS3 controller.

**Comment by Yook74** [comment]
This is designed for a PS4 controller (this is spelled out in the readme). I don't have a PS3 controller to test it with unfortunately so you're on your own unless you can find a PS4 controller.

**Comment by Yook74** [comment]
Sorry, I apparently didn't mention that in the readme. I'll make that change.

**Comment by ogmkp** [comment]
Ok, I haven't PS4 controller, but it seems compatible. Let me try with another computer. Maybe a dependency loosing in this debian.

**Comment by ogmkp** [comment]
The PS3 controller works in this script on another debian computer, I have to find why.
When i press X, the script answers:
```
Press triangle to configure cameras or any other button to skip
Traceback (most recent call last):
  File "/home/ogal/visca-joystick/main.py", line 155, in <module>
    cam = connect_to_camera(0)
  File "/home/ogal/visca-joystick/main.py", line 106, in connect_to_camera
    cam = Camera(ips[cam_index])
  File "/home/ogal/.local/lib/python3.9/site-packages/visca_over_ip/caching_camera.py", line 12, in __init__
    'focus_mode': super().get_focus_mode(),
  File "/home/ogal/.local/lib/python3.9/site-packages/visca_over_ip/camera.py", line 607, in get_focus_mode
    response = self._send_command('04 38', query=True)
  File "/home/ogal/.local/lib/python3.9/site-packages/visca_over_ip/camera.py", line 68, in _send_command
    raise NoQueryResponse(f'Could not get a response after {self.num_retries} tries')
visca_over_ip.exceptions.NoQueryResponse: Could not get a response after 5 tries
```

**Comment by Yook74** [comment]
That means it's not able to communicate with the camera. Can you ping your camera from your machine?

**Comment by ogmkp** [comment]
Yes and the camera ping and works with https://github.com/misterhay/VISCA-IP-Controller-GUI.
Maybe we need a port implementation ? The cam run on UDP 52381.

**Comment by Yook74** [comment]
52381 is the port it uses by default so that's not the issue. misterhay's project and mine both use the same code to interface with the controller so something is probably wrong with your setup. A few things to check:
1. Is the camera on?
2. Do you have the IP address set correctly in `config.py`?
3. do you have an unreliable or slow network between yourself and the camera?
4. Do you have another instance of this software running or is misterhay's software running? Having two or more running at the same time could cause this problem.

**Comment by ogmkp** [comment]
For all the steps: yes it's good.
I opened wireshark, I see that there are exchanges between the script and the camera. There must be something at VISCA level.
I don't know what the script is asking to initiate the communication. Can you give me a procedure to see what the camera responds, with netcat by example ?

**Comment by Yook74** [comment]
Can you send the Wireshark captures? What model of camera are you using?

**Comment by ogmkp** [comment]
Here you will find the capture.
[visca2.pcapng.zip](https://github.com/International-Anglican-Church/visca-joystick/files/8126957/visca2.pcapng.zip)

The camera does not have a model. It is a noname.

**Comment by Yook74** [comment]
Your camera does not appear to be responding with a sequence number, which is a violation of the VISCA-over-IP protocol in my understanding. Do you have any information at all about the camera you're using?

 I could provide a paired down version of this code that will work with your situation, I just need to understand why your camera is doing what it's doing.

**Comment by ogmkp** [comment]
I bought this camera a long time ago in the chinatown of Paris. I still use it because it still works. There is no label on it because it was cheap. I know that it does not send any ACKs to visca orders and that it does not respect the standards. But as it works with VISCA-IP-Controller-GUI I thought your project could work too. I would like to have the code adapted, that would be great!

**Comment by Yook74** [comment]
Try checking out the crappy_camera_support branch

**Comment by ogmkp** [comment]
The crappy_camera_support works great and with a PS3 controller ! I'll keep on testing thank you very much !

**Comment by ogmkp** [comment]
For the map part with the PS3 controller:
Left stick = Pan & Tilt (works fine)
Right stick = brightness (horizontally)
R2 trigger: zoom (but one step forward, one step back)
PS button: Tilt invert
Select button: exit

**Comment by Yook74** [comment]
You'll have to adjust the bindings in config.py. let me know what works for your controller and I can add it to the repository

**Comment by ogmkp** [comment]
Sure, for my PS3 controller I find this:
```
if platform.system() == 'Linux':
    mappings = {
        'cam_select': {1: 0, 2: 1, 3: 2},
        'movement': {'pan': 0, 'tilt': 1, 'zoom': 4},
        'brightness': {'up': 3, 'down': 4},
        'other': {'exit': 8, 'invert_tilt': 11, 'configure': 9}
    }
```
Sensitivity:
```
sensitivity_tables = {
    'pan': {'joy': [0, 0.3, 0.5, 0.7, 0.9, 1], 'cam': [0, 1, 4, 8, 16, 20]},
    'tilt': {'joy': [0, 0.3, 0.5, 0.7, 0.9, 1], 'cam': [0, 1, 4, 8, 16, 20]},
    'zoom': {'joy': [0, 0.9, 1], 'cam': [0, 7, 7]},
}
```
Pan/tilt works very great !
But, the zoom (right joystick) zooms step by step and is not fluid when I push the stick to 1.
Brightness (pad) don't work.
And, do you think I can map focus (infinite or onepush) since you removed the feature ?

Thank you for your help.

**Comment by Yook74** [comment]
Do you get smoother zooming with the visca GUI app?

The brightness adjustment is really adjusting the exposure compensation. It depends on your having the camera set to auto brightness I think.

I maybe could re-add the focus feature if you think that's something you use. What behavior would you like to have?

**Comment by ogmkp** [comment]
Zooming is smooth now, maybe it was a problem with the camera.
I can adjust the focus and exposure manually via the web interface. I'll keep testing and let you know if I find any more problems.
